---
- hosts: all
  gather_facts: true
  connection: network_cli
  ignore_errors: true
  name: L3 Interface merged with flash_synchro (true)
  vars:
    ansible_aos_write_memory_flash  : false
    ansible_aos_flash_synchro_flag : false
  tasks:
    - name: Run L3 interfaces resource module with state merged
      ale.aos8.aos8_l3_interfaces:
        config:
          - name: intvl20
            address: 192.168.33.1
            mask: 255.255.255.0
            type: vlan
            port_id: 20
        state: merged



