---
authors:
  - Alcatel-Lucent Enterprise Development Team
dependencies:
  "ansible.netcommon": ">=6.0.0"
license_file: LICENSE
name: aos8
namespace: ale
description: Ansible Network Collection for Alcatel-Lucent Enterprise AOS 8 devices.
readme: README.md
repository: https://github.com/ansible-collections/ale.aos8
issues: https://github.com/ansible-collections/ale.aos8/issues
tags: [ale, aos, aos8, networking]
version: "1.0.0"
