---
- hosts: all
  gather_facts: true
  ignore_errors: true
  name: Trap Manager merged with flash_synchro (true)
  vars:
    ansible_aos_write_memory_flash  : false
    ansible_aos_flash_synchro_flag : false
  tasks:
    - name: Run Trap Manager resource module with state merged
      ale.aos8.aos8_trap_managers:
        config:
          - host: 192.168.2.52
            port: 162
            version: v3
            string: snmpwrite
            state: enable
        state: merged


